[Writable]
LogLevel = 'INFO'
# InsecureSecrets are required for when Redis is used for message bus
[Writable.InsecureSecrets]
[Writable.InsecureSecrets.Sample]
path = "redisdb"
[Writable.InsecureSecrets.Sample.Secrets]
username = ""
password = ""

[Service]
HealthCheckInterval = '10s'
Host = 'localhost'
Port = 59982
ServerBindAddr = ''  # blank value defaults to Service.Host value
StartupMsg = 'device template started'
# MaxRequestSize limit the request body size in byte of put command
MaxRequestSize = 0 # value 0 unlimit the request size.
RequestTimeout = '5s'

[Registry]
Host = 'localhost'
Port = 8500
Type = 'consul'

[Clients]
[Clients.core-data]
Protocol = 'http'
Host = 'localhost'
Port = 59880

[Clients.core-metadata]
Protocol = 'http'
Host = 'localhost'
Port = 59881

[MessageQueue]
Protocol = 'redis'
Host = 'localhost'
Port = 6379
Type = 'redis'
AuthMode = 'usernamepassword'  # required for redis messagebus (secure or insecure).
SecretName = "redisdb"
PublishTopicPrefix = 'edgex/events/device' # /<device-profile-name>/<device-name>/<source-name> will be added to this Publish Topic prefix

[SecretStore]
Type = 'vault'
Host = 'localhost'
Port = 8200
Path = 'device-template/'
Protocol = 'http'
RootCaCertPath = ''
ServerName = ''
TokenFile = '/tmp/edgex/secrets/device-template/secrets-token.json'
[SecretStore.Authentication]
AuthType = 'X-Vault-Token'

[Device]
DataTransform = true
InitCmd = ''
InitCmdArgs = ''
MaxCmdOps = 128
MaxCmdValueLen = 256
RemoveCmd = ''
RemoveCmdArgs = ''
ProfilesDir = ''
DevicesDir = ''
UpdateLastConnected = false
Labels = []
EnableAsyncReadings = true
AsyncBufferSize = 16
UseMessageBus = false
